"""empty message

Revision ID: 627b649181d0
Revises: 0b93e4aadcc2
Create Date: 2021-04-01 23:10:32.928914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627b649181d0'
down_revision = '0b93e4aadcc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=80), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
