import os

DEBUG = True
SQLALCHEMY_DATABASE_URI = os.environ['DATABASE_URL']
SQLALCHEMY_TRACK_MODIFICATIONS = True
JWT_SCRECT_KEY = os.environ['JWT_SECRET_KEY']
SCRECT_KEY = os.environ['APP_SECRET_KEY']
JWT_BLACKLIST_ENABLED = True
JWT_BLACKLIST_TOKEN_CHECKS = ['access','refresh']